apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-slave-jjb
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jenkins-slave-jjb
  spec:
    source:
      type: Git
      git:
        uri: "https://github.com/rhoar-ci/jenkins-slave-jjb"
        ref: master
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: "jenkins-slave-jjb:latest"
